- src/leiningen/new/chestnut/env/prod/clj/chestnut/dev.clj
In the dev source path's `{{project-ns}}.dev` ns, the `is-dev?` var is a boolean, but in the production source's `{{project-ns.dev}}` ns, it was a function.
> Make is-dev? a boolean value, rather than function

- src/leiningen/new/chestnut/project.clj
This version contains new cljs.repl.node. You can start a ClojureScript Node.js REPL by using a script such as the example provided by the Mies Leiningen template: https://github.com/swannodette/mies/blob/master/src/leiningen/new/mies/compile_cljsc
> Update ClojureScript dependency to 0.0-2644.

- src/leiningen/new/chestnut/project.clj
Google Closure returns an error indicating duplicate externs file when using :optimizations advanced, this is due to the externs being already included by Om in deps.clj. David Nolen has explained it in this mail thread https://www.mail-archive.com/clojurescript@googlegroups.com/msg03826.html
> Removed cljsbuild externs for React.js.

- src/leiningen/new/chestnut/project.clj
I wasn't able to get the 0.0-2644 version of ClojureScript to work with 0.8.0-rc1 (and/or the SNAPSHOT version of Chestnut). I reverted the ClojureScript version to the one included with Om 0.8.0-rc1, which his 2511 (the version included in this change).
For the record, the error I got when starting the "browser-repl" (weasel + piggieback), via the Lein REPL, is listed here:
```` clojure
server=> (browser-repl)
<< started Weasel server on ws://0.0.0.0:9001 >>
Type `:cljs/quit` to stop the ClojureScript REPL
ArityException Wrong number of args (2) passed to: repl/fn--5122/self--5128  clojure.lang.AFn.throwArity (AFn.java:429)
````
> Revert ClojureScript version to latest that works with Om 0.8.0-rc1.

- src/leiningen/new/chestnut/env/prod/clj/chestnut/dev.clj
Fixes #72 
In a wider sense, I'm wondering if it might be better to move all dev init logic out of `server`.  Perhaps, `env/dev/{{name}}/dev-server.clj` contains the auto-reload init code and its own `run` function.  Thoughts?
> Stub start-less and start-sass in prod env

- src/leiningen/new/chestnut/env/dev/clj/chestnut/dev.clj
Now Om depends on cljsjs.react, it gets compiled into app.js. No need to include the script separately.
Without this change, in dev, `react.js` is requested, but the response is the `index.html` html, thus resulting in `Uncaught SyntaxError: Unexpected token <` with the browser attempting to evaluate the html as js.
See: https://github.com/omcljs/om/commit/b549554964fe5b53189222e97e77fc2db34aebd6#diff-0fff143854a4f5c0469a3819b978a483
> Remove react.js injection in dev html

- src/leiningen/new/chestnut/env/dev/clj/chestnut/dev.clj
This simple change seems to fix issue #106 for me.
> Fix order of source paths in figwheel autobuilds

- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/project.clj
Fixes #116.
Added a clj-test-src-path variable to the data map.  Renamed the
clojurescript test-src-path to be prefixed with 'cljs-'.
> Set test-paths correctly for Speclj and clojure.test

- src/leiningen/new/chestnut/project.clj
- src/leiningen/new/chestnut/src/clj/chestnut/server.clj
Fixing the uberjar so that "java -jar ..." actually runs the server instead of starting a REPL, on the assumption that this is the intention.
Also, fixing server startup message.
> Having the uberjar run the server

- src/leiningen/new/chestnut/env/dev/clj/chestnut/dev.clj
Using (run) from the REPL does not result in source maps being generated. This change to the profile fixes the issue.
Sorry for a fresh PR, I am not sure how to (or even if you can) squash commits once it's been PR'd.
> Out of the box, source maps are not generated when using figwheel. (#2)

- src/leiningen/new/chestnut/project.clj
Adds the `:ring-handler` key to the figwheel configuration. See #122.
> Update project.clj to fix #122

- README.md
- src/leiningen/new/chestnut/project.clj
I've changed the version of clojurescript from 1.7.122 to 1.7.145 since 1.7.122 does not exists in clojar any more.
I've also changed the version of om to 1.0.0-alpha14.
Please merge my code.
> change versions of clojurescript and om to the latest

- src/leiningen/new/chestnut/project.clj
Cljsbuild clean has been deprecated.
Add lein stanza to clean path resources/public/js
This was found in an attempt at getting a sense of pushing out artifacts. After messing in the browser-repl, `lein uberjar` was pushing out the old js, and I was getting some interesting `goog not defined` errors.
I attempted `lein cljsbuild clean` but it's listed as deprecated now.
https://github.com/emezeske/lein-cljsbuild/issues/376
per http://clojureverse.org/t/how-to-upgrade-from-0-7-to-0-8/47/4 a force `rm -rf resources/public/js` works but I would expect a clean to do this for me.
> clean task to remove resources/public/js

- src/leiningen/new/chestnut.clj
Fix omission of om dependency when http-kit option was invoked
> Fixed project-clj-deps function

- src/leiningen/new/chestnut/project.clj
This avoids FileNotFoundException when running "lein jar".
"lein uberjar" was unaffected as it replaces source-paths.
> Only include dev source path when dev profile is active

- README.md
- project.clj
- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/project.clj
Relying on profile merging is not recommended because it doesn't play
well with Figwheel. While our old setup worked, it encourages people to
put cljsbuild stuff in profiles, causing them to run into all kinds of
random issues.
Closes #172
> Avoid using profile merging for `:cljsbuild` config

- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/dev/user.clj
- src/leiningen/new/chestnut/project.clj
- src/leiningen/new/chestnut/src/clj/chestnut/server.clj
...and reloaded.repl
- no longer integrate figwheel into same ring handler. Much easier to separate figwheel from the system's ring handler.
- add doo to dev dependencies for cljsbuild
- version bump for figwheel... allow figwheel system to take the result of (config/fetch-config)
First stab at integrating chestnut with component and system by way of reloaded.repl.
Not everything is tested, but basic templates are working. As it is running under component now, rather than relying on wrap-reload for restarting the server, reloading the server (within the system) now depends on a reloaded.repl/reset call.
Hoping this helps kickstart efforts on integration with component. Let me know what you think!
I also started prototyping a [reloaded.repl like library in …
> integrating chestnut with components, system

- src/leiningen/new/chestnut/project.clj
According to lein-auto documentation:
> :paths - list of directories scanned for files. (defaults to concatenation of project :source-paths, :java-source-paths and :test-paths).'
None of those contain src/scss in our project.clj.
> Fix lein-auto configuraton for SCSS compilation

- src/leiningen/new/chestnut/project.clj
- src/leiningen/new/chestnut/src/clj/chestnut/application.clj
0.3.2 of system came with a breaking change to middleware handlers.
https://github.com/danielsz/system/issues/48#issuecomment-270248608
PR with the version bump to save you from a case of the 'where did my wrap-defaults middleware go's ;)
> system version bump 0.4.0

- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/dev/cljs/user.cljs
- src/leiningen/new/chestnut/project.clj
- src/leiningen/new/chestnut/resources/public/index.html
- src/leiningen/new/chestnut/src/cljs/chestnut/components/render.cljs
- src/leiningen/new/chestnut/src/cljs/chestnut/core_om.cljs
- src/leiningen/new/chestnut/src/cljs/chestnut/core_om_next.cljs
- src/leiningen/new/chestnut/src/cljs/chestnut/core_reagent.cljs
- src/leiningen/new/chestnut/src/cljs/chestnut/core_rum.cljs
- src/leiningen/new/chestnut/src/cljs/chestnut/core_vanilla.cljs
- src/leiningen/new/chestnut/src/cljs/chestnut/system.cljs
Here's a working proof of concept with system integration for cljs for you to review. I've been favoring this setup in a personal project and the patch here is a simple port back to chestnut.
Go ahead and see how you like this. In general, I'd love to hear what you're envisioning for component integration on the cljs side, and I hope this patch is a good starting point for discussion.
- This is currently dependent on my cljs fork of reloaded.repl.
- I've modified the repl :init to run (go) for dev ease. This can go if it's unwanted.
- The sample component and system is copy-pasted to each of the cljs templates. Currently this system prints out messages on start/stop. I'm *sure* there's a better way to do this bit.
- I've added a dev/cljs/user.cljs for dev builds that refers to the …
> Cljs system integration

- CHANGELOG.md
- README.md
- project.clj
- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/project.clj
- src/leiningen/new/chestnut/src/cljs/chestnut/core_re_frame.cljs
Adds a re-frame flag which adds re-frame as a dependency, and creates the
typical re-frame structure of db/subs/views/events.
This uses the templates directly from re-frame-template. At the moment only the
basic vanilla re-frame template is supported, but it would be easy to add
support for +re-frisk or +re-com.
> re-frame support (experimental)

- CHANGELOG.md
- README.md
- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/dev/user.clj
- src/leiningen/new/chestnut/project.clj
- src/leiningen/new/chestnut/src/clj/chestnut/application.clj
- src/leiningen/new/chestnut/src/clj/chestnut/components/shell_component.clj
- src/leiningen/new/chestnut/src/clj/chestnut/config.clj
- src/leiningen/new/chestnut/src/clj/chestnut/routes.clj
Just starting a REPL should not start the system, otherwise it becomes impossible to run multiple repls in parallel. Chestnut has always had an extra step to kick things into gear (before: `(run)`, now: `(go)`), and I think that's the better way to do things.
These two features were contributed to Chestnut, but always felt like a hack, both on the Chestnut implementation side (they didn't follow the conventions that other feature flags use), and in the generated code (calling lein through clojure.java.shell/sh, really?) 
It's still a hack, but one that at least kind of follows the established conventions. I've introduced a ShellComponent so that they can take part in the component lifecycle instead of doing their own thing. This still uses clojure.java.shell/sh, meaning you can't …
> Pre 0.15.0 changes

- src/leiningen/new/chestnut/README.md
This is to make clear that Figwheel server is not the app server.
> Update README with app server info

- src/leiningen/new/chestnut/project.clj
This prevents an exception with a plain new project:
Caused by: java.io.FileNotFoundException: Could not locate
ring/core/protocols__init.class or ring/core/protocols.clj on classpath.,
compiling:(ring/util/servlet.clj:1:1)
> Update figwheel to 0.5.11

- src/leiningen/new/chestnut/.gitignore
- src/leiningen/new/chestnut/dev/user.clj
- src/leiningen/new/chestnut/project.clj
Add dev-target js compiling folder to disallow cljs name conflicts during a
reload. dev-target feels like the best name to mirror 'target', but I am open to discussion here.
Re-enable wrap-reload in the dev environment, allowing routes to reload automatically on change, without a system restart.
This is in an effort to address some of the [issues brought up on the mailing list.](http://clojureverse.org/t/pain-points-in-current-chestnut/402)
> Make cljc code reloadable.

- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/src/clj/chestnut/application.clj
- src/leiningen/new/chestnut/src/clj/chestnut/components/server_info.clj
Have a component that prints out where the server starts, so it gets printed when the system starts, rather than when main is called. This adds an info line to how to connect to your application, even when main isn't called (eg, starting from the repl, in dev mode).
Not against a redirect, but I feel like there should be some sort of print line in any environment.
(Partially) Addresses [the first point brought up on the mailing list](http://clojureverse.org/t/pain-points-in-current-chestnut/402).
This might be overkill - we could alternatively just print in an overridden `(go)` function, or something of that nature, but this ensures that we print the message every time the system is started.
> add an info component to print where to connect to the application

- CHANGELOG.md
- README.md
- project.clj
- repl/ancient.clj
- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/project.clj
Add `+edge` and `+bleeding-edge` options, powered by `ancient-clj`, which automatically make sure all libraries are at their latest version.
`+bleeding-edge` includes SNAPSHOT versions, `+edge` does not.
Also includes some helper code for updating all dependencies used inside Chestnut, so it's easier to keep the template up to date.
> Bleeding edge option

- .gitignore
- CHANGELOG.md
- repl/ancient.clj
- src/leiningen/new/chestnut.clj
First time the ancient repl script is being put to use. The diff is still a bit messy because the ordering in the optional deps changed, they're sorted now so that shouldn't be a problem in the future.
I manually reverted any alpha/beta versions back to their latest stable, except for Om which we had in alpha and is now in beta. This is something we might want to hack into the script to happen automatically.
> Upgrade ClojureScript, Om, Reagent, lein-cljsbuild, Figwheel

- src/leiningen/new/chestnut/dev/user.clj
We need to wrap-file at its earliest so that subsequent
middleware (eg, wrap-mime) is applied properly to hosted files from
this path.
(Service workers for instance check for a valid mime type on registration.)
> Fix development middleware order

- src/leiningen/new/chestnut.clj
Adds a default log setup through onelogger.
this dependency no longer is shipped with the newer version of
ring.middleware.logger, so we need to explicitly include it.
closes #218
> add logger by default

- src/leiningen/new/chestnut/README.md
This corrects the generated README's shell command for watching scss files.
> correct sassc build command

- CHANGELOG.md
- project.clj
Bump snapshot version
New project under lein 1.8 throws:
`Could not load template, failed with: java.io.FileNotFoundException:
Could not locate slingshot/slingshot__init.class or
slingshot/slingshot.clj on classpath.,
compiling:(clj_http/client.clj:1:1)`
see https://github.com/xsc/lein-ancient/issues/80
> Lein 1.8 fixes

- README.md
- src/leiningen/new/chestnut.clj
- src/leiningen/new/chestnut/src/clj/chestnut/application.clj
- src/leiningen/new/chestnut/src/clj/chestnut/routes.clj
I prefer to use `bidi` for server side routing library rather than `Compojure`.
So I tried to support this as command line option `+bidi`.
When `+bidi` not specified, generates files for `Compojure`.
I prefer to use `bidi` for server side routing libraries instead of` Compojure`.
So I tried supporting it as a command line option `+ bidi`.
If `+ bidi` is not specified, it creates conventional` Compojure` files.
> bidi support

- project.clj
- src/leiningen/new/chestnut.clj
bumping cljs removes xml hack
bumping clj keeps pace with cljs versioning, and for later java stability.
bumping transit as older versions don't work with newer cljs versions
bumping garden watcher fixes base watching issue
bumping all templates to support react16
bumping ring - security fixes
> bump dependencies

- src/leiningen/new/chestnut/.dir-locals.el
The vars `cider-refresh-before-fn` and `cider-refresh-after-fn` are obsolete since 0.18: https://github.com/clojure-emacs/cider/blob/master/cider-ns.el#L104
It seems like using those variables should still work, but before these changes, `cider-ns-refresh` only printed "Don't know how to make a localized variable an alias” (see https://stackoverflow.com/questions/52191455/calling-cider-refresh-shows-dont-know-how-to-make-a-localized-variable-an-alia)
After these changes (and an emacs restart), `cider-ns-refresh` worked again.
> Update CIDER vars in .dir-locals.el

- src/leiningen/new/chestnut/project.clj
Starting a REPL on a new project times out (issue #243). This increases
the timeout for starting the REPL to 5 minutes.
> Increase REPL timeout to 5 minutes
